name: ticket_app_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-339.0.dev <4.0.0"

dependencies:
  bloc_test: ^9.1.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  go_router: ^6.2.0
  test: ^1.23.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
