name: ticket_app_web
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  formz: ^0.6.0
  freezed_annotation: ^2.2.0
  go_router: ^6.2.0
  test: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2

flutter:
  uses-material-design: true
